### ISSUE TITLE
Search box corners are too rounded and unstable on iOS Safari

### ISSUE THREAD

**Issue by wholesomedev** [hollowverse-archive/hollowverse#243] opened 2018-01-07 00:29 UTC
When I search for an NP on iOS Safari, the search box corners are too rounded and as I type they alternate between more and less rounded!

**Comment by forabi** [comment] 2018-01-10 19:53
I can confirm this. I'm working on configuring remote debugging of Safari iOS so that I can inspect the search box in DevTools and see what's going on.

**Comment by forabi** [comment] 2018-01-11 19:58
So... I've set up remote debugging for Safari and inspected the search input. It turns out that Safari applies some styles for `<input />` if `type="search"`. While setting the type to `"text"` fixes the round corners, it will hide the "Search" button that shows on on-screen keyboard. A [better fix](https://stackoverflow.com/posts/2918716/revisions) is to set:

```
 -webkit-appearance: none;
```

This will be fixed in #230

**Comment by forabi** [comment] 2018-01-25 22:13
Fixed by #230

**Closed as completed by forabi** 2018-01-25 22:13 UTC
